# Generated by Django 3.1.5 on 2021-01-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210120_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyrate',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.panel'),
        ),
    ]
