# Generated by Django 3.1.5 on 2021-01-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210120_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlyrate',
            name='user',
        ),
        migrations.AddField(
            model_name='panel',
            name='hourlyRate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.hourlyrate'),
        ),
    ]
