# Generated by Django 3.1.5 on 2021-01-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210120_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourlyRate', models.CharField(max_length=10)),
                ('overtimeRate', models.CharField(max_length=10)),
                ('weekendRate', models.CharField(max_length=10)),
                ('bankHolidayRate', models.CharField(max_length=10)),
                ('specialRate', models.CharField(max_length=10)),
                ('holidayPay', models.CharField(max_length=10)),
                ('sickPay', models.CharField(max_length=10)),
                ('grossPay', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='panel',
            name='hourlyRate',
        ),
        migrations.DeleteModel(
            name='HourlyRate',
        ),
        migrations.AddField(
            model_name='panel',
            name='rates',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.rates'),
        ),
    ]
