# Generated by Django 3.1.5 on 2021-01-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_servicedetails_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
