# Generated by Django 3.1.5 on 2021-01-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_delete_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
