# Generated by Django 3.1.5 on 2021-02-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_address', models.CharField(max_length=100)),
                ('business_information', models.CharField(max_length=100)),
                ('customer_information', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_reference', models.CharField(max_length=100)),
                ('po_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=1000)),
                ('due_date', models.DateField()),
                ('company_number', models.CharField(max_length=100)),
                ('vat_number', models.CharField(max_length=100)),
                ('bank_account_no', models.CharField(max_length=100)),
                ('sort_code_no', models.CharField(max_length=100)),
            ],
        ),
    ]
