# Generated by Django 3.1.5 on 2021-01-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210125_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='charges',
        ),
    ]
