# Generated by Django 3.1.5 on 2021-01-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210125_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employee2'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stipend',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
