# Generated by Django 3.1.5 on 2021-02-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210125_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_info', models.CharField(max_length=100)),
                ('supplier_address', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
